# Generated by BoostInstall.cmake for boost_crc-1.86.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_crc ${boost_crc_VERSION} at ${boost_crc_DIR}")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_crc-targets.cmake")
