# Generated by BoostInstall.cmake for boost_qvm-1.86.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_qvm ${boost_qvm_VERSION} at ${boost_qvm_DIR}")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_qvm-targets.cmake")
