# Generated by BoostInstall.cmake for boost_yap-1.86.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_yap ${boost_yap_VERSION} at ${boost_yap_DIR}")
endif()

include(CMakeFindDependencyMacro)

if(NOT boost_hana_FOUND)
  find_dependency(boost_hana 1.86.0 EXACT HINTS "${CMAKE_CURRENT_LIST_DIR}/..")
endif()
if(NOT boost_preprocessor_FOUND)
  find_dependency(boost_preprocessor 1.86.0 EXACT HINTS "${CMAKE_CURRENT_LIST_DIR}/..")
endif()
if(NOT boost_type_index_FOUND)
  find_dependency(boost_type_index 1.86.0 EXACT HINTS "${CMAKE_CURRENT_LIST_DIR}/..")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_yap-targets.cmake")
