# Generated by BoostInstall.cmake for boost_compatibility-1.86.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_compatibility ${boost_compatibility_VERSION} at ${boost_compatibility_DIR}")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_compatibility-targets.cmake")
