# Generated by BoostInstall.cmake for boost_callable_traits-1.86.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_callable_traits ${boost_callable_traits_VERSION} at ${boost_callable_traits_DIR}")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_callable_traits-targets.cmake")
