# Generated by BoostInstall.cmake for boost_vmd-1.86.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_vmd ${boost_vmd_VERSION} at ${boost_vmd_DIR}")
endif()

include(CMakeFindDependencyMacro)

if(NOT boost_preprocessor_FOUND)
  find_dependency(boost_preprocessor 1.86.0 EXACT HINTS "${CMAKE_CURRENT_LIST_DIR}/..")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_vmd-targets.cmake")
