# Generated by BoostInstall.cmake for boost_python-1.86.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_python ${boost_python_VERSION} at ${boost_python_DIR}")
endif()

include(CMakeFindDependencyMacro)

if(NOT boost_python311_FOUND)
  find_dependency(boost_python311 1.86.0 EXACT HINTS "${CMAKE_CURRENT_LIST_DIR}/..")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_python-targets.cmake")
