# Generated by BoostInstall.cmake for boost_hof-1.86.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_hof ${boost_hof_VERSION} at ${boost_hof_DIR}")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_hof-targets.cmake")
