# Generated by BoostInstall.cmake for boost_stacktrace-1.88.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_stacktrace ${boost_stacktrace_VERSION} at ${boost_stacktrace_DIR}")
endif()

include(CMakeFindDependencyMacro)

if(NOT boost_stacktrace_windbg_FOUND)
  find_dependency(boost_stacktrace_windbg 1.88.0 EXACT HINTS "${CMAKE_CURRENT_LIST_DIR}/..")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_stacktrace-targets.cmake")
