# Generated by BoostInstall.cmake for boost_lambda2-1.86.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_lambda2 ${boost_lambda2_VERSION} at ${boost_lambda2_DIR}")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_lambda2-targets.cmake")
