# Generated by BoostInstall.cmake for boost_leaf-1.86.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_leaf ${boost_leaf_VERSION} at ${boost_leaf_DIR}")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_leaf-targets.cmake")
