# Generated by BoostInstall.cmake for boost_pfr-1.86.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_pfr ${boost_pfr_VERSION} at ${boost_pfr_DIR}")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_pfr-targets.cmake")
